backend:
  image: ahmed12shire/lmsbe1
  port: 8080
  targetPort: 8080
  nodePort: 30007
  mode: production
frontend:
  image: ahmed12shire/lmsfe2
  port: 80
  targetPort: 80
  nodePort: 30008
configmap:
  name: backend-configmap
  namespace: default